steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'
      - '-f'
      - './services/$_SERVICE_NAME/Dockerfile'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'

options:
  logging: CLOUD_LOGGING_ONLY
