steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/web'
      - '-f'
      - './apps/web/Dockerfile'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/web'

options:
  logging: CLOUD_LOGGING_ONLY
