# GrandGold CI/CD - Build and deploy on push to main
# Connect GitHub repo in GCP Console > Cloud Build > Triggers

steps:
  # Build auth-service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/auth-service:$SHORT_SHA'
      - '-f'
      - './services/auth-service/Dockerfile'
      - '.'
    id: 'build-auth'

  # Build product-service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/product-service:$SHORT_SHA'
      - '-f'
      - './services/product-service/Dockerfile'
      - '.'
    id: 'build-product'

  # Build order-service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/order-service:$SHORT_SHA'
      - '-f'
      - './services/order-service/Dockerfile'
      - '.'
    id: 'build-order'

  # Build web (with production backend URLs so /api/cart, /api/auth, etc. proxy correctly)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/web:$SHORT_SHA'
      - '-f'
      - './apps/web/Dockerfile'
      - '--build-arg'
      - 'NEXT_PUBLIC_AUTH_SERVICE_URL=https://auth-service-484382472654.asia-south1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_ORDER_SERVICE_URL=https://order-service-484382472654.asia-south1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_PRODUCT_SERVICE_URL=https://product-service-484382472654.asia-south1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_KYC_SERVICE_URL=https://auth-service-484382472654.asia-south1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_SELLER_SERVICE_URL=https://auth-service-484382472654.asia-south1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_FINTECH_SERVICE_URL=https://auth-service-484382472654.asia-south1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_PAYMENT_SERVICE_URL=https://auth-service-484382472654.asia-south1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_INVENTORY_SERVICE_URL=https://product-service-484382472654.asia-south1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_AI_SERVICE_URL=https://product-service-484382472654.asia-south1.run.app'
      - '.'
    id: 'build-web'

  # Push images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/auth-service:$SHORT_SHA']
    id: 'push-auth'
    waitFor: ['build-auth']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/product-service:$SHORT_SHA']
    id: 'push-product'
    waitFor: ['build-product']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/order-service:$SHORT_SHA']
    id: 'push-order'
    waitFor: ['build-order']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/web:$SHORT_SHA']
    id: 'push-web'
    waitFor: ['build-web']

  # Deploy to asia-south1
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy auth-service --image gcr.io/$PROJECT_ID/auth-service:$SHORT_SHA --region asia-south1 --platform managed --quiet
        gcloud run deploy product-service --image gcr.io/$PROJECT_ID/product-service:$SHORT_SHA --region asia-south1 --platform managed --quiet
        gcloud run deploy order-service --image gcr.io/$PROJECT_ID/order-service:$SHORT_SHA --region asia-south1 --platform managed --quiet
        gcloud run deploy web --image gcr.io/$PROJECT_ID/web:$SHORT_SHA --region asia-south1 --platform managed --quiet
    id: 'deploy'
    waitFor: ['push-auth', 'push-product', 'push-order', 'push-web']

images:
  - 'gcr.io/$PROJECT_ID/auth-service:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/product-service:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/order-service:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/web:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '2400s'
